version: '3'
services:
  app:
    build: .
    command: npm start
    restart: always
    container_name: app-matches
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/api
    working_dir: /usr/api
  db:
    image: mongo
    restart: always
    container_name: db-matches
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
